version: "2.2"
services:
  web:
    container_name: openedx.devstack.learner_portal
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - .:/edx/app:delegated
      - notused:/edx/app/node_modules
    ports:
      - "8734:8734"
    environment:
      - NODE_ENV=development
    network_mode: host
volumes:
  notused:
